project_id = "xlyflmvfwanwukhycfqs"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = true

[functions.trading-bot-api]
verify_jwt = false

[functions.tts-narration]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
